import type { Question } from "@/lib/questions/types";

/** 內建題庫：答案都是數字或是非，老師不匯入也能直接玩 */
export const MORSE_QUESTIONS: Question[] = [
  {
    id: "m1",
    type: "choice",
    text: "一年有幾個月？",
    options: ["10", "11", "12", "13"],
    answer: "12",
    difficulty: "easy",
  },
  {
    id: "m2",
    type: "choice",
    text: "一打雞蛋有幾顆？",
    options: ["6", "10", "12", "24"],
    answer: "12",
    difficulty: "easy",
  },
  {
    id: "m3",
    type: "boolean",
    text: "一星期有 7 天。",
    answer: "是",
    difficulty: "easy",
  },
  {
    id: "m4",
    type: "choice",
    text: "三角形有幾條邊？",
    options: ["2", "3", "4", "5"],
    answer: "3",
    difficulty: "easy",
  },
  {
    id: "m5",
    type: "choice",
    text: "九九乘法中，8 × 7 等於多少？",
    options: ["54", "56", "58", "64"],
    answer: "56",
    difficulty: "normal",
  },
  {
    id: "m6",
    type: "boolean",
    text: "一公尺等於 100 公分。",
    answer: "是",
    difficulty: "normal",
  },
  {
    id: "m7",
    type: "choice",
    text: "正方形有幾條對稱軸？",
    options: ["2", "3", "4", "6"],
    answer: "4",
    difficulty: "normal",
  },
  {
    id: "m8",
    type: "choice",
    text: "一小時有幾分鐘？",
    options: ["30", "45", "60", "100"],
    answer: "60",
    difficulty: "normal",
  },
  {
    id: "m9",
    type: "choice",
    text: "平角是幾度？",
    options: ["90", "120", "180", "360"],
    answer: "180",
    difficulty: "hard",
  },
  {
    id: "m10",
    type: "boolean",
    text: "質數 13 大於 10 且小於 20。",
    answer: "是",
    difficulty: "hard",
  },
  {
    id: "m11",
    type: "choice",
    text: "一公里是幾公尺？",
    options: ["100", "500", "1000", "10000"],
    answer: "1000",
    difficulty: "hard",
  },
  {
    id: "m12",
    type: "choice",
    text: "144 的平方根是多少？",
    options: ["10", "11", "12", "14"],
    answer: "12",
    difficulty: "hard",
  },
];
