import type { Question } from "./types";

/**
 * 內建題庫：國小中年級通識（自然、社會、數學、語文、生活常識）。
 * 用途是讓沒有自備 Excel 的老師能一鍵開場，不打算做成可編輯資料。
 */
export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "d1",
    type: "choice",
    text: "台灣最高的山是哪一座？",
    options: ["玉山", "雪山", "阿里山", "陽明山"],
    answer: "玉山",
    explanation: "玉山主峰海拔 3952 公尺，是台灣最高峰。",
  },
  {
    id: "d2",
    type: "choice",
    text: "一年之中有幾個月有 31 天？",
    options: ["5 個月", "6 個月", "7 個月", "8 個月"],
    answer: "7 個月",
    explanation: "1、3、5、7、8、10、12 月共 7 個月。",
  },
  {
    id: "d3",
    type: "boolean",
    text: "蝙蝠是鳥類。",
    answer: "否",
    explanation: "蝙蝠會餵母乳，屬於哺乳類。",
  },
  {
    id: "d4",
    type: "short",
    text: "水在攝氏幾度會結冰？",
    answer: "0 度",
    explanation: "一大氣壓下，水的凝固點是攝氏 0 度。",
  },
  {
    id: "d5",
    type: "choice",
    text: "彩虹的顏色由外而內，最外圈是什麼顏色？",
    options: ["紅色", "紫色", "綠色", "黃色"],
    answer: "紅色",
    explanation: "紅光偏折角度最小，出現在彩虹最外圈。",
  },
  {
    id: "d6",
    type: "boolean",
    text: "地球繞著太陽轉一圈大約要一年。",
    answer: "是",
    explanation: "公轉一圈約 365.25 天，所以有閏年。",
  },
  {
    id: "d7",
    type: "short",
    text: "7 乘以 8 等於多少？",
    answer: "56",
  },
  {
    id: "d8",
    type: "choice",
    text: "下列哪一個不是台灣的直轄市？",
    options: ["新竹市", "台中市", "高雄市", "桃園市"],
    answer: "新竹市",
    explanation: "新竹市是省轄市，全台目前有 6 個直轄市。",
  },
  {
    id: "d9",
    type: "boolean",
    text: "月亮會自己發光。",
    answer: "否",
    explanation: "月亮是反射太陽光才亮的。",
  },
  {
    id: "d10",
    type: "choice",
    text: "人體最大的器官是什麼？",
    options: ["皮膚", "肝臟", "肺臟", "心臟"],
    answer: "皮膚",
    explanation: "皮膚包覆全身，面積與重量都最大。",
  },
  {
    id: "d11",
    type: "short",
    text: "一個星期有幾天？",
    answer: "7 天",
  },
  {
    id: "d12",
    type: "choice",
    text: "「守株待兔」這個成語是在形容什麼？",
    options: [
      "不知變通、空等機會",
      "做事很有耐心",
      "動作非常敏捷",
      "團隊合作愉快",
    ],
    answer: "不知變通、空等機會",
    explanation: "出自農夫等兔子再撞樹的寓言。",
  },
  {
    id: "d13",
    type: "boolean",
    text: "植物行光合作用會放出氧氣。",
    answer: "是",
    explanation: "光合作用吸收二氧化碳、放出氧氣。",
  },
  {
    id: "d14",
    type: "choice",
    text: "台灣的形狀常被形容像什麼？",
    options: ["蕃薯", "香蕉", "鳳梨", "西瓜"],
    answer: "蕃薯",
  },
  {
    id: "d15",
    type: "short",
    text: "一公斤等於幾公克？",
    answer: "1000 公克",
  },
  {
    id: "d16",
    type: "boolean",
    text: "垃圾分類時，寶特瓶應該丟一般垃圾。",
    answer: "否",
    explanation: "寶特瓶屬於可回收的資源垃圾。",
  },
  {
    id: "d17",
    type: "choice",
    text: "下列哪一種動物是兩棲類？",
    options: ["青蛙", "蜥蜴", "海豚", "企鵝"],
    answer: "青蛙",
    explanation: "青蛙小時候用鰓呼吸，長大用肺，屬兩棲類。",
  },
  {
    id: "d18",
    type: "short",
    text: "三角形的內角和是幾度？",
    answer: "180 度",
  },
  {
    id: "d19",
    type: "choice",
    text: "打 119 是要找誰？",
    options: ["消防隊", "警察局", "電力公司", "郵局"],
    answer: "消防隊",
    explanation: "119 是火警與救護，110 才是報警。",
  },
  {
    id: "d20",
    type: "boolean",
    text: "台灣位於北半球。",
    answer: "是",
  },
  {
    id: "d21",
    type: "choice",
    text: "一天當中，太陽從哪個方向升起？",
    options: ["東方", "西方", "南方", "北方"],
    answer: "東方",
  },
  {
    id: "d22",
    type: "short",
    text: "100 減去 37 等於多少？",
    answer: "63",
  },
  {
    id: "d23",
    type: "boolean",
    text: "颱風在台灣多半發生在冬天。",
    answer: "否",
    explanation: "颱風季主要在夏季到初秋。",
  },
  {
    id: "d24",
    type: "choice",
    text: "「一年之計在於春」的下一句常接什麼？",
    options: [
      "一日之計在於晨",
      "一寸光陰一寸金",
      "盡信書不如無書",
      "萬事起頭難",
    ],
    answer: "一日之計在於晨",
  },
  {
    id: "d25",
    type: "choice",
    text: "下列哪一個是可再生能源？",
    options: ["太陽能", "石油", "煤炭", "天然氣"],
    answer: "太陽能",
    explanation: "太陽能取之不盡，其餘三種是化石燃料。",
  },
  {
    id: "d26",
    type: "short",
    text: "正方形有幾條邊？",
    answer: "4 條",
  },
  {
    id: "d27",
    type: "boolean",
    text: "過馬路時綠燈亮了就可以完全不用看左右來車。",
    answer: "否",
    explanation: "綠燈仍要左右確認，可能有轉彎車。",
  },
  {
    id: "d28",
    type: "choice",
    text: "蜜蜂採蜜時，順便幫植物做了什麼事？",
    options: ["傳播花粉", "澆水", "施肥", "除草"],
    answer: "傳播花粉",
  },
  {
    id: "d29",
    type: "short",
    text: "農曆正月初一是哪一個節日？",
    answer: "春節",
  },
  {
    id: "d30",
    type: "choice",
    text: "下列哪一個習慣最能省水？",
    options: [
      "洗米水拿來澆花",
      "水龍頭開著刷牙",
      "用流動的水解凍",
      "每天洗澡泡澡一小時",
    ],
    answer: "洗米水拿來澆花",
  },
];
